config/routes.rb
Rails.application.routes.draw do
  root 'cards#index'
  get '/card/:id1/:id2' => 'charts#index'
  get '/cards/:id1/:id2' => 'cards#show'
  
  devise_for :users
  resources :posts
  resources :cards
  
  resources :charts, only: [] do
    collection do
      get 'results_by_barchart'
      get 'results_by_piechart'
    end
  end
  

end

app/models/card.rb
class Card < ActiveRecord::Base
    belongs_to :user
    mount_uploader :avatar, AvatarUploader
    resourcify
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
 before_action :set_card, only: [:show, :edit, :destroy, :update]
   load_and_authorize_resource

    def index
      @cards = Card.all
    end
    
    def new 
      @card = Card.new
    end
    
    def create
      @card = Card.new(card_params)
      if @card.save
          redirect_to cards_path
      else 
          flash[:alert] = "Failed to save"
          redirect_to :back
      end
    end

    def update
      if @card.update(card_params)
        redirect_to cards_path
      else 
        flash[:alert] = "Failed to save"
        redirect_to :back
      end
    end
    
    def edit
      @card = Card.where("id = '#{params[:id1]}'")
    end

    def show
      @card = Card.find_by(card_id: params[:id1], card_name: params[:id2])
    end
    
    def destroy
      if @card.destroy
        redirect_to cards_path
      else
        flash[:alert] = "Failed to delete"
      end
    end
    
    private
    def card_params
        params.require(:card).permit(:card_id, :card_name, :content, 
        :score1, :score2, :score3, :score4, :score5, :avatar)
    end
    
    def set_card
        @card = Card.find_by(card_id: params[:id])
    end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_form.html.erb
<br><br><br><br>
<%= flash[:alert] %>
<%= form_for(@card) do |f| %>
    카드사
    <%= f.text_field :card_id, class: "form-control", placeholder: "카드사 이름을 입력해주세요" %><br>
    카드이름
    <%= f.text_field :card_name, class: "form-control", placeholder: "카드 이름을 입력해주세요" %><br>
    상세 카드 혜택:
    <%= f.text_area :content, class: "form-control",placeholder: "상세한 카드 혜택을 입력해주세요" %><br>

    주유 점수: <%= f.number_field :score1, class: "form-control", placeholder: "주유 점수를 입력해주세요" %><br>
    쇼핑 점수: <%= f.number_field :score2, class: "form-control", placeholder: "쇼핑 점수를 입력해주세요" %><br>
    외식 점수: <%= f.number_field :score3, class: "form-control", placeholder: "외식 점수를 입력해주세요" %><br>
    캐시백 점수: <%= f.number_field :score4, class: "form-control", placeholder: "캐시백 점수를 입력해주세요" %><br>
    마일리지 점수: <%= f.number_field :score5, class: "form-control", placeholder: "마일리지 점수를 입력해주세요" %><br>
    
    <%= f.file_field :avatar %><br>
    
    <%= f.hidden_field :user_id, :value => current_user.id %>
    <%= f.submit "작성하기", class: "btn btn-success"%><br><br>
<% end %>

app/views/cards/edit.html.erb
<%= render partial: "form" %>

app/views/cards/index.html.erb
<!DOCTYPE HTML>
<!--
	Autonomy by TEMPLATED
    templated.co @templatedco
    Released for free under the Creative Commons Attribution 3.0 license (templated.co/license)
-->
<html>
	<head>
		<title>Autonomy by TEMPLATED</title>
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<meta name="description" content="" />
		<meta name="keywords" content="" />
		<link href='http://fonts.googleapis.com/css?family=Raleway:400,100,200,300,500,600,700,800,900' rel='stylesheet' type='text/css'>
		<!--[if lte IE 8]><script src="js/html5shiv.js"></script><![endif]-->
		<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
		<script src="js/skel.min.js"></script>
		<script src="js/skel-panels.min.js"></script>
		<script src="js/init.js"></script>
		<noscript>
			<link rel="stylesheet" href="css/skel-noscript.css" />
			<link rel="stylesheet" href="css/style.css" />
			<link rel="stylesheet" href="css/style-desktop.css" />
		</noscript>
		<!--[if lte IE 8]><link rel="stylesheet" href="css/ie/v8.css" /><![endif]-->
		<!--[if lte IE 9]><link rel="stylesheet" href="css/ie/v9.css" /><![endif]-->
	</head>
	<body class="homepage">
		<div id="banner">
			
		</div>

		<div id="featured">
			<div class="card">
				<ul class="nav nav-tabs" id="myTab" role="tablist">
				  <li class="nav-item">
				    <a class="nav-link" data-toggle="tab" href="#c1" role="tab" aria-controls="c1">신한</a>
				  </li>
				  <li class="nav-item">
				    <a class="nav-link" data-toggle="tab" href="#c2" role="tab" aria-controls="c2">현대</a>
				  </li>
				  <li class="nav-item">
				    <a class="nav-link" data-toggle="tab" href="#c3" role="tab" aria-controls="c3">삼성</a>
				  </li>
				  <li class="nav-item">
				    <a class="nav-link" data-toggle="tab" href="#c4" role="tab" aria-controls="c4">롯데</a>
				  </li>
				  <li class="nav-item">
				    <a class="nav-link" data-toggle="tab" href="#c5" role="tab" aria-controls="c5">씨티</a>
				  </li>
				  <li class="nav-item">
				    <a class="nav-link" data-toggle="tab" href="#c6" role="tab" aria-controls="c6">하나</a>
				  </li>
				  <li class="nav-item">
				    <a class="nav-link" data-toggle="tab" href="#c7" role="tab" aria-controls="c7">우리</a>
				  </li>
				  <li class="nav-item">
				    <a class="nav-link" data-toggle="tab" href="#c8" role="tab" aria-controls="c8">KB국민</a>
				  </li>
				  <li class="nav-item">
				    <a class="nav-link" data-toggle="tab" href="#c9" role="tab" aria-controls="c9">NH농협</a>
				  </li>
				  <li class="nav-item">
				    <a class="nav-link" data-toggle="tab" href="#c10" role="tab" aria-controls="c10">IBK기업</a>
				  </li>
				</ul>
				
				<br><br><br>
				<div class="tab-content">
					
				  <div class="tab-pane fade" id="c1" role="tabpanel">
				  	<div class="container">
				  		<div class="row">
				  			<% @cards.where("card_id = '신한'").each do |c| %>
					            <div class="col-lg-4 col-md-4 col-sm-6 portfolio-item">
					                <div class="card h-100">
					                    <a href='/card/<%=c.card_id%>/<%=c.card_name%>'><%= image_tag c.avatar.url, :size => '260x180' %></a><br>
					                    <div class="card-body">
					                        <h4 class="card-title"><a href='/card/<%=c.card_id%>/<%=c.card_name%>'> <%=c.card_name%> </a></h4>
					                    </div>
					                </div><br>
					            </div>
						  	<% end %>
				  		</div>
				  	</div>
				  </div>
				  
				  <div class="tab-pane fade" id="c2" role="tabpanel">
				  	<div class="container">
				  		<div class="row">
				  			<% @cards.where("card_id = '현대'").each do |c| %>
					            <div class="col-lg-4 col-md-4 col-sm-6 portfolio-item">
					                <div class="card h-100">
					                    <a href='/card/<%=c.card_id%>/<%=c.card_name%>'><%= image_tag c.avatar.url, :size => '260x180' %></a><br>
					                    <div class="card-body">
					                        <h4 class="card-title"><a href='/card/<%=c.card_id%>/<%=c.card_name%>'> <%=c.card_name%> </a></h4>
					                    </div>
					                </div><br>
					            </div>
						  	<% end %>
				  		</div>
				  	</div>
				  </div>
				  
				  <div class="tab-pane fade" id="c3" role="tabpanel">
				  	<div class="container">
				  		<div class="row">
				  			<% @cards.where("card_id = '삼성'").each do |c| %>
					            <div class="col-lg-4 col-md-4 col-sm-6 portfolio-item">
					                <div class="card h-100">
					                    <a href='/card/<%=c.card_id%>/<%=c.card_name%>'><%= image_tag c.avatar.url, :size => '260x180' %></a><br>
					                    <div class="card-body">
					                        <h4 class="card-title"><a href='/card/<%=c.card_id%>/<%=c.card_name%>'> <%=c.card_name%> </a></h4>
					                    </div>
					                </div><br>
					            </div>
						  	<% end %>
				  		</div>
				  	</div>
				  </div>
				  
				  <div class="tab-pane fade" id="c4" role="tabpanel">
				  	<div class="container">
				  		<div class="row">
				  			<% @cards.where("card_id = '롯데'").each do |c| %>
					            <div class="col-lg-4 col-md-4 col-sm-6 portfolio-item">
					                <div class="card h-100">
					                    <a href='/card/<%=c.card_id%>/<%=c.card_name%>'><%= image_tag c.avatar.url, :size => '260x180' %></a><br>
					                    <div class="card-body">
					                        <h4 class="card-title"><a href='/card/<%=c.card_id%>/<%=c.card_name%>'> <%=c.card_name%> </a></h4>
					                    </div>
					                </div><br>
					            </div>
						  	<% end %>
				  		</div>
				  	</div>
				  </div>
				  
				  <div class="tab-pane fade" id="c5" role="tabpanel">
				  	<div class="container">
				  		<div class="row">
				  			<% @cards.where("card_id = '씨티'").each do |c| %>
					            <div class="col-lg-4 col-md-4 col-sm-6 portfolio-item">
					                <div class="card h-100">
					                    <a href='/card/<%=c.card_id%>/<%=c.card_name%>'><%= image_tag c.avatar.url, :size => '260x180' %></a><br>
					                    <div class="card-body">
					                        <h4 class="card-title"><a href='/card/<%=c.card_id%>/<%=c.card_name%>'> <%=c.card_name%> </a></h4>
					                    </div>
					                </div><br>
					            </div>
						  	<% end %>
				  		</div>
				  	</div>
				  </div>
				  
				  <div class="tab-pane fade" id="c6" role="tabpanel">
				  	<div class="container">
				  		<div class="row">
				  			<% @cards.where("card_id = '하나'").each do |c| %>
					            <div class="col-lg-4 col-md-4 col-sm-6 portfolio-item">
					                <div class="card h-100">
					                    <a href='/card/<%=c.card_id%>/<%=c.card_name%>'><%= image_tag c.avatar.url, :size => '260x180' %></a><br>
					                    <div class="card-body">
					                        <h4 class="card-title"><a href='/card/<%=c.card_id%>/<%=c.card_name%>'> <%=c.card_name%> </a></h4>
					                    </div>
					                </div><br>
					            </div>
						  	<% end %>
				  		</div>
				  	</div>
				  </div>
				  
				  <div class="tab-pane fade" id="c7" role="tabpanel">
				  	<div class="container">
				  		<div class="row">
				  			<% @cards.where("card_id = '우리'").each do |c| %>
					            <div class="col-lg-4 col-md-4 col-sm-6 portfolio-item">
					                <div class="card h-100">
					                    <a href='/card/<%=c.card_id%>/<%=c.card_name%>'><%= image_tag c.avatar.url, :size => '260x180' %></a><br>
					                    <div class="card-body">
					                        <h4 class="card-title"><a href='/card/<%=c.card_id%>/<%=c.card_name%>'> <%=c.card_name%> </a></h4>
					                    </div>
					                </div><br>
					            </div>
						  	<% end %>
				  		</div>
				  	</div>
				  </div>
				  
				  <div class="tab-pane fade" id="c8" role="tabpanel">
				  	<div class="container">
				  		<div class="row">
				  			<% @cards.where("card_id = 'KB국민'").each do |c| %>
					            <div class="col-lg-4 col-md-4 col-sm-6 portfolio-item">
					                <div class="card h-100">
					                    <a href='/card/<%=c.card_id%>/<%=c.card_name%>'><%= image_tag c.avatar.url, :size => '260x180' %></a><br>
					                    <div class="card-body">
					                        <h4 class="card-title"><a href='/card/<%=c.card_id%>/<%=c.card_name%>'> <%=c.card_name%> </a></h4>
					                    </div>
					                </div><br>
					            </div>
						  	<% end %>
				  		</div>
				  	</div>
				  </div>
				  
				  <div class="tab-pane fade" id="c9" role="tabpanel">
				  	<div class="container">
				  		<div class="row">
				  			<% @cards.where("card_id = 'NH농협'").each do |c| %>
					            <div class="col-lg-4 col-md-4 col-sm-6 portfolio-item">
					                <div class="card h-100">
					                    <a href='/card/<%=c.card_id%>/<%=c.card_name%>'><%= image_tag c.avatar.url, :size => '260x180' %></a><br>
					                    <div class="card-body">
					                        <h4 class="card-title"><a href='/card/<%=c.card_id%>/<%=c.card_name%>'> <%=c.card_name%> </a></h4>
					                    </div>
					                </div><br>
					            </div>
						  	<% end %>
				  		</div>
				  	</div>
				  </div>
				  
				  <div class="tab-pane fade" id="c10" role="tabpanel">
				  	<div class="container">
				  		<div class="row">
				  			<% @cards.where("card_id = 'IBK기업'").each do |c| %>
					            <div class="col-lg-4 col-md-4 col-sm-6 portfolio-item">
					                <div class="card h-100">
					                    <a href='/card/<%=c.card_id%>/<%=c.card_name%>'><%= image_tag c.avatar.url, :size => '260x180' %></a><br>
					                    <div class="card-body">
					                        <h4 class="card-title"><a href='/card/<%=c.card_id%>/<%=c.card_name%>'> <%=c.card_name%> </a></h4>
					                    </div>
					                </div><br>
					            </div>
						  	<% end %>
				  		</div>
				  	</div>
				  </div>
				  
				</div>
			</div>
			
		  
              
	            <% if user_signed_in? && current_user.has_role?(:admin) %>
		            <div class="jumbotron">
		              <%= link_to "새로운 카드 정보 등록", new_card_path, class: "btn btn-default btn-lg" %>
		            </div>
         	    <% end %>
        	 
		
		<!-- Copyright -->
		<div id="copyright">
			<div class="container">
				Design: <a href="http://templated.co">멋쟁이사자처럼5기 돈벌자팀</a> Images: <a href="http://unsplash.com">Unsplash</a> (<a href="http://unsplash.com/cc0">CC0</a>)
			</div>
		</div>
		
	<script>
	  $(function () {
	    $('#myTab a:last').tab('show')
	  })
	</script>
	</body>
</html>

app/views/cards/index1.html.erb
<!DOCTYPE HTML>
<!--
	Autonomy by TEMPLATED
    templated.co @templatedco
    Released for free under the Creative Commons Attribution 3.0 license (templated.co/license)
-->
<html>
	<head>
		<title>Autonomy by TEMPLATED</title>
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<meta name="description" content="" />
		<meta name="keywords" content="" />
		<link href='http://fonts.googleapis.com/css?family=Raleway:400,100,200,300,500,600,700,800,900' rel='stylesheet' type='text/css'>
		<!--[if lte IE 8]><script src="js/html5shiv.js"></script><![endif]-->
		<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
		<script src="js/skel.min.js"></script>
		<script src="js/skel-panels.min.js"></script>
		<script src="js/init.js"></script>
		<noscript>
			<link rel="stylesheet" href="css/skel-noscript.css" />
			<link rel="stylesheet" href="css/style.css" />
			<link rel="stylesheet" href="css/style-desktop.css" />
		</noscript>
		<!--[if lte IE 8]><link rel="stylesheet" href="css/ie/v8.css" /><![endif]-->
		<!--[if lte IE 9]><link rel="stylesheet" href="css/ie/v9.css" /><![endif]-->
	</head>
	<body class="homepage">
		


		<div id="banner">
			
		</div>

		<div id="featured">
			<div class="card">
				
				<ul class="nav nav-tabs" id="myTab" role="tablist">
				  <li class="nav-item">
				    <a class="nav-link active" data-toggle="tab" href="#c1" role="tab" aria-controls="c1">신한</a>
				  </li>
				  <li class="nav-item">
				    <a class="nav-link" data-toggle="tab" href="#c2" role="tab" aria-controls="c2">현대</a>
				  </li>
				  <li class="nav-item">
				    <a class="nav-link" data-toggle="tab" href="#c3" role="tab" aria-controls="c3">삼성</a>
				  </li>
				  <li class="nav-item">
				    <a class="nav-link" data-toggle="tab" href="#c4" role="tab" aria-controls="c4">롯데</a>
				  </li>
				  <li class="nav-item">
				    <a class="nav-link" data-toggle="tab" href="#c5" role="tab" aria-controls="c5">씨티</a>
				  </li>
				  <li class="nav-item">
				    <a class="nav-link" data-toggle="tab" href="#c6" role="tab" aria-controls="c6">하나</a>
				  </li>
				  <li class="nav-item">
				    <a class="nav-link" data-toggle="tab" href="#c7" role="tab" aria-controls="c7">우리</a>
				  </li>
				  <li class="nav-item">
				    <a class="nav-link" data-toggle="tab" href="#c8" role="tab" aria-controls="c8">KB국민</a>
				  </li>
				  <li class="nav-item">
				    <a class="nav-link" data-toggle="tab" href="#c9" role="tab" aria-controls="c9">NH농협</a>
				  </li>
				  <li class="nav-item">
				    <a class="nav-link" data-toggle="tab" href="#c10" role="tab" aria-controls="c10">IBK기업</a>
				  </li>
				</ul>
				
				<div class="tab-content">
				  <div class="tab-pane active" id="c1" role="tabpanel">
				  	<% @cards.where("card_id = '신한'").each do |c| %>
				  		<%= image_tag c.avatar.url, :size => '260x180' %>
				  	<% end %>
				  </div>
				  <div class="tab-pane" id="c2" role="tabpanel">
				  	<% @cards.where("card_id = '현대'").each do |c| %>
				  		<%= image_tag c.avatar.url, :size => '260x180' %><br>
				  	<% end %>
				  </div>
				  <div class="tab-pane" id="c3" role="tabpanel">
				  	<% @cards.where("card_id = '삼성'").each do |c| %>
				  		<%= image_tag c.avatar.url, :size => '260x180' %><br>
				  	<% end %>
				  </div>
				  <div class="tab-pane" id="c4" role="tabpanel">
				  	<% @cards.where("card_id = '롯데'").each do |c| %>
				  		<%= image_tag c.avatar.url, :size => '260x180' %><br>
				  	<% end %>
				  </div>
				  <div class="tab-pane" id="c5" role="tabpanel">
				  	<% @cards.where("card_id = '씨티'").each do |c| %>
				  		<%= image_tag c.avatar.url, :size => '260x180' %><br>
				  	<% end %>
				  </div>
				  <div class="tab-pane" id="c6" role="tabpanel">
				  	<% @cards.where("card_id = '하나'").each do |c| %>
				  		<%= image_tag c.avatar.url, :size => '260x180' %><br>
				  	<% end %>
				  </div>
				  <div class="tab-pane" id="c7" role="tabpanel">
				  	<% @cards.where("card_id = '우리'").each do |c| %>
				  		<%= image_tag c.avatar.url, :size => '260x180' %><br>
				  	<% end %>
				  </div>
				  <div class="tab-pane" id="c8" role="tabpanel">
				  	<% @cards.where("card_id = 'KB국민'").each do |c| %>
				  		<%= image_tag c.avatar.url, :size => '260x180' %><br>
				  	<% end %>
				  </div>
				  <div class="tab-pane" id="c9" role="tabpanel">
				  	<% @cards.where("card_id = 'NH농협'").each do |c| %>
				  		<%= image_tag c.avatar.url, :size => '260x180' %><br>
				  	<% end %>
				  </div>
				  <div class="tab-pane" id="c10" role="tabpanel">
				  	<% @cards.where("card_id = 'IBK기업'").each do |c| %>
				  		<%= image_tag c.avatar.url, :size => '260x180' %><br>
				  	<% end %>
				  </div>
				</div>
			</div>
			
			<% if user_signed_in? && current_user.has_role?(:admin) %>
		      <div class="jumbotron">
		        <%= link_to "새로운 카드 정보 등록", new_card_path, class: "btn btn-primary btn-lg" %>
		      </div>
		     <% end %>

			<div class="container">
				<div class="row">

					<div class="3u">
						<section>
							
							<a href="#" class="image full">
								
							<% @cards.where(card_id:'신한').find_each do |card| %>
                
                                 <p> <%= image_tag card.avatar.url, :size => '260x180' %> </p>
                                    
                                <a href="/card/<%=card.card_id%>/<%=card.card_name%>">  <%= card.card_name %>  </a>
                            <% end %>
							<header>
								<h2>Etiam posuere</h2>
							</header>
										
						</section>
					</div>

					<!--<div class="3u">-->
					<!--	<section>-->
					<!--		<a href="#" class="image full"><img src="/app/assets/images/pics03.jpg" alt=""></a>-->
					<!--		<header>-->
					<!--			<h2>Fusce ultrices</h2>-->
					<!--		</header>-->
					<!--		<p>Pellentesque tristique ante. Sed vel tellus. Curabitur sem urna, consequat suscipit mattis placerat, nulla.</p>				-->
					<!--	</section>-->
					<!--</div>-->
					
					<!--<div class="3u">-->
					<!--	<section>-->
					<!--		<a href="#" class="image full"><img src="/app/assets/images/pics03.jpg" alt=""></a>-->
					<!--		<header>-->
					<!--			<h2>Fusce ultrices</h2>-->
					<!--		</header>-->
					<!--		<p>Pellentesque tristique ante. Sed vel tellus. Curabitur sem urna, consequat suscipit mattis placerat, nulla.</p>				-->
					<!--	</section>-->
					<!--</div>-->
					
					<!--<div class="3u">-->
					<!--	<section>-->
					<!--		<a href="#" class="image full"><img src="/app/assets/images/pics03.jpg" alt=""></a>-->
					<!--		<header>-->
					<!--			<h2>Fusce ultrices</h2>-->
					<!--		</header>-->
					<!--		<p>Pellentesque tristique ante. Sed vel tellus. Curabitur sem urna, consequat suscipit mattis placerat, nulla.</p>				-->
					<!--	</section>-->
					<!--</div>-->
					
				
					
		<!-- Copyright -->
		<div id="copyright">
			<div class="container">
				Design: <a href="http://templated.co">멋쟁이사자처럼5기 돈벌자팀</a> Images: <a href="http://unsplash.com">Unsplash</a> (<a href="http://unsplash.com/cc0">CC0</a>)
			</div>
		</div>
		
	<script>
	  $(function () {
	    $('#myTab a:last').tab('show')
	  })
	</script>
	</body>
</html>

app/views/cards/new.html.erb
<%= render partial: "form" %>

app/views/cards/show.html.erb
<head>
    <link type="text/css" rel="stylesheet" href="show.css"/>
</head>

<br><br><br>

<div class = "container">


  <div class="row">
    	<div class="col-lg-12">
						<h1 class="page-header">카드 혜택 상세보기
         <%= flash[:alert] %>
         <small>카드사: <%= @card.card_id %> | 카드이름: <%= @card.card_name %></small>
         </h1>
						
		  </div>
  </div>
  
  <div class="row">
    <div class="col-md-6">
        <div class="container" align="center">
           <%= image_tag @card.avatar.url, :size => '500x350' %>
        </div>
    
    </div>

    <div class="col-md-6">
        <div class="form-group has-success has-feedback">
           <h3>상세 카드 혜택</h3>
           <br>
           <p>
              <%= @card.content %> 
           </p>
           
           <p>
               <% if user_signed_in? && current_user.has_role?(:admin) %>
                <%= link_to '수정', edit_card_path(@card), class: "btn btn-default" %>
                <%= link_to '삭제', card_path(@card), method: :delete, data: {confirm: "정말 삭제하시겠습니까?"}, class: "btn btn-default"%>
               <%end%>
           </p>
                     
           </div>
                  
                      
         
        </div>
    </div>           
 </div>
</div>