config/routes.rb
Rails.application.routes.draw do
  root 'cards#index'
  get '/card/:id1/:id2' => 'charts#index'
  get '/cards/:id1/:id2' => 'cards#show'
  
  devise_for :users
  resources :posts
  resources :cards
  
  resources :charts, only: [] do
    collection do
      get 'results_by_barchart'
      get 'results_by_piechart'
    end
  end
  

end

app/models/post.rb
class Post < ActiveRecord::Base
    belongs_to :user
    resourcify
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.order("created_at DESC").page params[:page]
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.email = current_user.email

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:name, :title, :content, :email)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field content_height">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field_block submit_field_block actions" id="form_submit_block">
    <a><%= f.submit %></a> |
    <%= link_to 'Back', posts_path %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="ss_box ss_form ss_even" data-widget="form" id="form">
  <div class="ss_box_content ss_form_content" id="content_form">
    <div id="wrapper">
      <div class="ss_container main" data-widget="container" id="container">
        <div class="ss_container_content">
          <div class="ss_box ss_rich_text ss_odd" data-widget="rich_text2" id="rich_text2">
            <div class="ss_container ss_layout ss_layout_2col container_bg" data-widget="two_column" id="two_column">
              <div class="ss_container_content ss_layout_content ss_layout_2col_content">
                <div class="ss_box_content ss_rich_text_content" id="content_rich_text">
                  <p id="notice"><%= notice %></p>
                  <h1>Editing Post</h1>
                </div>
              </div>
          </div>
          <div class="ss_box ss_form ss_even" data-widget="form" id="form">
            <div class="ss_box_content ss_form_content" id="content_form">
              <%= render 'form' %>
              <br>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/posts/index.html.erb
<div class="ss_box ss_form ss_even" data-widget="form" id="form">
  <div class="ss_box_content ss_form_content" id="content_form">
    <div id="wrapper">
      <div class="ss_container main" data-widget="container" id="container">
        <div class="ss_container_content">
          <div class="ss_box ss_rich_text ss_odd" data-widget="rich_text2" id="rich_text2">
            <div class="ss_container ss_layout ss_layout_2col container_bg" data-widget="two_column" id="two_column">
              <div class="ss_container_content ss_layout_content ss_layout_2col_content">
                <div class="ss_container ss_layout_column" data-widget="column" id="column" style="width: 50%;">
                  <div class="ss_container_content">
                    <div class="ss_box ss_image ss_odd" data-widget="image" id="image">
                      <div class="ss_box_content ss_image_content ss_align_left" id="content_image">
                        <div class="ss_image_container">
                          <%=image_tag("review.png", alt: "Example Image")%>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="ss_container ss_layout_column" data-widget="column2" id="column2" style="width: 50%;">
                  <div class="ss_container_content">
                    <div class="ss_box ss_rich_text ss_even" data-widget="rich_text" id="rich_text">
                      <div class="ss_box_content ss_rich_text_content" id="content_rich_text">
                        <p id="notice"><%= notice %></p>
                        <div class="ss_box_content ss_rich_text_content" id="content_rich_text2">
                          <h1>Review Post!</h1>
                          <p>Please your opinion for us.</p>
                        </div>
                      </div>
                   </div>
                </div>
              </div>
            </div>
          </div>
          <div class="ss_box ss_form ss_even" data-widget="form" id="form">
            
              <table>
                <thead>
                  <tr>
                    <th width="40px;"></th>
                    <th class="text_center">Title</th>
                    <th class="text_center" width="200px;">Writer</th>
                    <th class="text_center" width="100px;">Date</th>
                  </tr>
                </thead>
              
                <tbody>
                  <% @posts.each do |post| %>
                    <tr class="height_20px">
                      <td><%= post.id %></td>
                      <td><%= link_to post.title, post %></td>
                      <td><%= post.email %></td>
                      <td class="text_center"><%= post.created_at.strftime("%Y-%m-%d") %></td>
                      
                    </tr>
                  <% end %>
                </tbody>
              </table>
              <br>
                <div class="field_block submit_field_block" id="form_submit_block">
                  <a href="/posts/new" id="link_1_links">New Post</a>
                </div>
              </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="ss_container" data-widget="container2" id="container2">
    <div class="ss_container_content">
      <div class="ss_container" data-widget="container3" id="container3">
        <div class="ss_container_content">
          <%= paginate @posts %>
        </div>
      </div>
    </div>
  </div>

app/views/posts/new.html.erb
<div class="ss_box ss_form ss_even" data-widget="form" id="form">
  <div class="ss_box_content ss_form_content" id="content_form">
    <div id="wrapper">
      <div class="ss_container main" data-widget="container" id="container">
        <div class="ss_container_content">
          <div class="ss_box ss_rich_text ss_odd" data-widget="rich_text2" id="rich_text2">
            <div class="ss_container ss_layout ss_layout_2col container_bg" data-widget="two_column" id="two_column">
              <div class="ss_container_content ss_layout_content ss_layout_2col_content">
                <div class="ss_box_content ss_rich_text_content" id="content_rich_text">
                  <p id="notice"><%= notice %></p>
                  <h1>New Post</h1>
                </div>
              </div>
          </div>
          <div class="ss_box ss_form ss_even" data-widget="form" id="form">
            <div class="ss_box_content ss_form_content" id="content_form">
              <%= render 'form' %>
              <br>
              
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/posts/show.html.erb
  <!-- 옮길거 -->
  <meta name="csrf-param" content="authenticity_token">
  <meta name="csrf-token" content="WoWCHK956p5V12+DC2EpjVt6sOk+tcRRZA+7lTQGfUI=">
  <meta content="text/html; charset=utf-8" http-equiv="Content-Type">
  
  <meta content="2017-07-19 10:13:07 -0700" name="revised">
  <meta name="ss-token" content="GVXGEZBZLLJvthtIR4Z7Sw==">
  <meta name="ss-timestamp" content="1501650968">
  
  <link href="https://d2xcq4qphg1ge9.cloudfront.net/themes/155264/campaign/5206470_9824_1500484368.css" media="screen" rel="stylesheet" type="text/css">
  <!-- /옮길거 -->
  
<div class="ss_box ss_form ss_even" data-widget="form" id="form">
  <div class="ss_box_content ss_form_content" id="content_form">
    <div id="wrapper">
      <div class="ss_container main" data-widget="container" id="container">
        <div class="ss_container_content">
          <div class="ss_box ss_rich_text ss_odd" data-widget="rich_text2" id="rich_text2">
            <div class="ss_container ss_layout ss_layout_2col container_bg" data-widget="two_column" id="two_column">
              <div class="ss_container_content ss_layout_content ss_layout_2col_content">
                <div class="ss_box_content ss_rich_text_content" id="content_rich_text">
                  <p id="notice"><%= notice %></p>
                </div>
              </div>
          </div>
          <div class="ss_box ss_form ss_even" data-widget="form" id="form">
            <div class="ss_box_content ss_form_content" id="content_form">
              <table>
                <thead>
                  <tr>
                    <th><%= @post.title %></th>
                    <th class="text_right" id="blur"><%= @post.created_at.strftime("%Y.%m.%d") %></th>
                  </tr>
                </thead>
              
                <tbody>
                  
                    <tr>
                      <td class="text_vertical" height="50px;">(Written_by) <%= @post.email %></td>
                    </tr>
                   <tr>
                      <td class="text_vertical" height="300px;"><%= @post.content %></td>
                    </tr>
                  <tr>
                    <td class="text_right" colspan="2"><%= link_to 'Edit', edit_post_path(@post) %> | <%= link_to 'Destroy', @post, method: :delete, data: { confirm: 'Are you sure?' } %> | <%= link_to 'Back', posts_path %></td>
                  </tr>
                </tbody>
              </table>
              <br>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  